#!/bin/sh
# File generated by ocamlbuild

cd /home/jigao/Desktop/IN0003_Tutorial/Week13

rm -f example.cmi
rm -f example.cmo
# Also clean the script itself
rm -f /home/jigao/Desktop/IN0003_Tutorial/Week13/_build/sanitize.sh
